# frontend/Dockerfile

# Define the base image
FROM node:18-alpine

# Set working directory
WORKDIR /app/frontend

# Install dependencies
COPY package*.json ./
RUN npm install --force

# Copy all files
COPY . .

# Build app
RUN npm run build

# Expose port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
