# backend/Dockerfile

# Define the base image
FROM python:3.11

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=config.settings.development
ENV PYLINT_ARGS="--load-plugins pylint_django"

# Set working directory
WORKDIR /app/backend

# Install dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Copy project
COPY . .

# Expose port
EXPOSE 8000

# Run the application:
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
